# Generated by Django 5.2.8 on 2025-11-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Faculty of Engineering & Technology",
                        max_length=255,
                    ),
                ),
                (
                    "dean",
                    models.CharField(
                        blank=True, help_text="Name of the Dean/Lead", max_length=100
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="e.g., North Campus, Block A",
                        max_length=100,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email for the faculty",
                        max_length=254,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Setup", "In Setup"),
                            ("Review", "Under Review"),
                            ("Archived", "Archived"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculties",
                        to="academic.institution",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Faculties",
                "ordering": ["name"],
            },
        ),
    ]
