# Generated by Django 5.2.8 on 2025-11-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="dean",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(help_text="e.g., BSCS", max_length=50)),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in years"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Certificate", "Certificate"),
                            ("Diploma", "Diploma"),
                            ("Bachelors", "Bachelors"),
                            ("Masters", "Masters"),
                            ("PhD", "PhD"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "coordinator",
                    models.CharField(
                        blank=True, help_text="Program Coordinator Name", max_length=100
                    ),
                ),
                ("student_capacity", models.PositiveIntegerField(default=0)),
                (
                    "modules",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of core modules"
                    ),
                ),
                ("entry_requirements", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="faculties.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("faculty", "code")},
            },
        ),
    ]
