# Generated by Django 5.2.8 on 2025-12-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0002_alter_faculty_dean_alter_faculty_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(blank=True, help_text="e.g. CS", max_length=50),
                ),
                ("head_of_department", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="faculties.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="program",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="program",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="faculties.department",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="program",
            unique_together={("department", "code")},
        ),
        migrations.RemoveField(
            model_name="program",
            name="faculty",
        ),
    ]
