# Generated by Django 5.2.8 on 2025-12-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0003_department_alter_program_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="annual_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Standard annual fee for this program",
                max_digits=10,
            ),
        ),
    ]
