# Generated by Django 5.2.8 on 2025-12-12 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_type", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("date_generated", models.DateField(auto_now_add=True)),
                ("created_by", models.CharField(default="Admin", max_length=100)),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/")),
            ],
        ),
    ]
