# Generated by Django 5.2.8 on 2025-12-17 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('enrollment', 'Enrollment'), ('academic', 'Academic Performance'), ('staff', 'Staff Analytics'), ('financial', 'Financial Overview')], max_length=50)),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reports_reporttemplate',
            },
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='date_generated',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='file',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='name',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='report_type',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='title',
            field=models.CharField(default='Untitled Report', max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='generatedreport',
            table='reports_generatedreport',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate'),
        ),
    ]
