# Generated by Django 5.2.8 on 2025-12-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reporttemplate_remove_generatedreport_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
