# Generated by Django 5.2.8 on 2025-12-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_generatedreport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='report_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
