# Generated by Django 5.2.8 on 2025-12-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_generatedreport_report_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedreport',
            name='file',
        ),
    ]
