import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Rocket, DollarSign, Users, TrendingUp } from "lucide-react";
import {
  PieChart,
  Pie,
  Cell,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { StatsCard } from "@/components/dashboard/StatsCard";
import { api } from "@/lib/api"; // same axios/fetch wrapper used in other pages

interface StartupStats {
  active_startups: number;
  total_revenue: string;
  people_employed: number;
  funding_acquired: string;
}

interface Startup {
  id: number;
  name: string;
  category: "Urban" | "Rural";
  institution: string;
  revenue_ytd: string;
  employed: number;
  status: "Pre-seed" | "Growth" | "Scaling" | "Stable";
}

const CATEGORY_COLORS = ["#6366f1", "#f59e0b"];
const STATUS_COLORS: Record<string, string> = {
  "Pre-seed": "#9ca3af",
  Growth: "#3b82f6",
  Scaling: "#22c55e",
  Stable: "#6366f1",
};

export default function Startups() {
  const [stats, setStats] = useState<StartupStats | null>(null);
  const [startups, setStartups] = useState<Startup[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        // Endpoints aligned with other dashboard pages
        const [statsRes, listRes] = await Promise.all([
          api.get("/startups/summary/"),
          api.get("/startups/")
        ]);

        setStats(statsRes.data);
        setStartups(listRes.data);
      } catch (error) {
        console.error("Failed to load startup data", error);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="pb-2 border-b">
          <h1 className="text-3xl font-bold flex items-center gap-2">
            <Rocket className="h-7 w-7 text-accent" />
            Startups & Commercialisation
          </h1>
          <p className="text-muted-foreground">
            Tracking economic impact, revenue, and employment generated by TESC-incubated ventures.
          </p>
        </div>

        {/* Key Metrics */}
        {!loading && stats && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <StatsCard
              title="Active Startups"
              value={stats.active_startups}
              description="Currently registered ventures"
              icon={Rocket}
              variant="accent"
            />
            <StatsCard
              title="Total Revenue"
              value={stats.total_revenue}
              description="Cumulative revenue generated"
              icon={DollarSign}
              variant="success"
            />
            <StatsCard
              title="People Employed"
              value={stats.people_employed}
              description="Jobs created directly"
              icon={Users}
              variant="info"
            />
            <StatsCard
              title="External Funding"
              value={stats.funding_acquired}
              description="Acquired in last 12 months"
              icon={TrendingUp}
              variant="default"
            />
          </div>
        )}

        {/* Analytics Charts */}
        {!loading && startups.length > 0 && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Category Distribution Pie */}
            <Card>
              <CardHeader>
                <CardTitle>Startup Distribution by Category</CardTitle>
              </CardHeader>
              <CardContent className="h-80">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={Object.values(
                        startups.reduce<Record<string, number>>((acc, s) => {
                          acc[s.category] = (acc[s.category] || 0) + 1;
                          return acc;
                        }, {})
                      ).map((value, index) => ({
                        name: Object.keys(
                          startups.reduce<Record<string, number>>((acc, s) => {
                            acc[s.category] = (acc[s.category] || 0) + 1;
                            return acc;
                          }, {})
                        )[index],
                        value,
                      }))}
                      dataKey="value"
                      nameKey="name"
                      outerRadius={110}
                      label
                    >
                      {Object.keys(
                        startups.reduce<Record<string, number>>((acc, s) => {
                          acc[s.category] = (acc[s.category] || 0) + 1;
                          return acc;
                        }, {})
                      ).map((_, index) => (
                        <Cell key={index} fill={CATEGORY_COLORS[index % CATEGORY_COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip />
                    <Legend />
                  </PieChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            {/* Employment by Startup Bar Chart */}
            <Card>
              <CardHeader>
                <CardTitle>Employment per Startup</CardTitle>
              </CardHeader>
              <CardContent className="h-80">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={startups}>
                    <XAxis dataKey="name" hide />
                    <YAxis />
                    <Tooltip />
                    <Legend />
                    <Bar dataKey="employed" name="Employees">
                      {startups.map((s, index) => (
                        <Cell key={index} fill={STATUS_COLORS[s.status]} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Startups Detail Table */}
        <Card>
          <CardHeader>
            <CardTitle>Detailed Startup Performance</CardTitle>
            <p className="text-sm text-muted-foreground">
              View financial status, employment, and focus areas.
            </p>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Startup Name</TableHead>
                  <TableHead>Institution</TableHead>
                  <TableHead>Category</TableHead>
                  <TableHead className="text-right">Revenue (YTD)</TableHead>
                  <TableHead className="text-center">Employed</TableHead>
                  <TableHead>Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {startups.map((startup) => (
                  <TableRow key={startup.id}>
                    <TableCell className="font-medium">{startup.name}</TableCell>
                    <TableCell>{startup.institution}</TableCell>
                    <TableCell>
                      <span
                        className={`px-2 py-1 text-xs font-medium rounded-full ${
                          startup.category === "Urban"
                            ? "bg-indigo-100 text-indigo-700"
                            : "bg-amber-100 text-amber-700"
                        }`}
                      >
                        {startup.category}
                      </span>
                    </TableCell>
                    <TableCell className="text-right font-medium">
                      {startup.revenue_ytd}
                    </TableCell>
                    <TableCell className="text-center">{startup.employed}</TableCell>
                    <TableCell>
                      <span
                        className={`px-2 py-1 text-xs font-medium rounded-full ${
                          startup.status === "Scaling"
                            ? "bg-green-100 text-green-700"
                            : startup.status === "Growth"
                            ? "bg-blue-100 text-blue-700"
                            : "bg-gray-100 text-gray-700"
                        }`}
                      >
                        {startup.status}
                      </span>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
