# Generated by Django 5.2.8 on 2025-12-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0008_institution_has_innovation_hub_institution_province"),
    ]

    operations = [
        migrations.CreateModel(
            name="InnovationHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("capacity", models.IntegerField(default=0)),
                ("occupied", models.IntegerField(default=0)),
                (
                    "services",
                    models.IntegerField(
                        default=0, help_text="Number of services offered"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("High", "High Activity"),
                            ("Medium", "Medium Activity"),
                            ("Full", "Full Capacity"),
                        ],
                        default="Medium",
                        max_length=50,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hubs",
                        to="academic.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_name", models.CharField(max_length=255)),
                ("focus_area", models.CharField(max_length=255)),
                ("agreement_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="Active", max_length=50)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships",
                        to="academic.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("team_name", models.CharField(blank=True, max_length=255)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("agritech", "Agriculture / AgriTech"),
                            ("edtech", "Education / EdTech"),
                            ("healthtech", "Health / BioTech"),
                            ("fintech", "FinTech"),
                            ("mining", "Mining & Engineering"),
                            ("energy", "Green Energy"),
                            ("manufacturing", "Manufacturing"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "location_category",
                    models.CharField(
                        choices=[("Urban", "Urban"), ("Rural", "Rural")],
                        default="Urban",
                        max_length=10,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("ideation", "Ideation"),
                            ("prototype", "Prototyping"),
                            ("incubation", "Incubation"),
                            ("market_ready", "Market Ready"),
                            ("scaling", "Scaling / Startup"),
                            ("industrial", "Industrialised"),
                        ],
                        default="ideation",
                        max_length=50,
                    ),
                ),
                ("problem_statement", models.TextField(blank=True)),
                ("proposed_solution", models.TextField(blank=True)),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "funding_acquired",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                ("jobs_created", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="innovation.innovationhub",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="academic.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("date_awarded", models.DateField()),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="academic.institution",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="innovation.project",
                    ),
                ),
            ],
        ),
    ]
