# Generated by Django 5.2.8 on 2025-12-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("innovation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="innovationhub",
            name="services",
        ),
    ]
