// const mockInnovations = [
//   {
//     id: "INN001",
//     title: "Smart Irrigation System",
//     category: "Agriculture Tech",
//     stage: "Incubation",
//     team: "AgriTech Innovators",
//     department: "Engineering",
//     problemStatement: "Inefficient water usage in farming leading to crop loss and water wastage",
//     solution: "IoT-based smart irrigation system that uses soil moisture sensors and weather data to optimize water usage",
//     impact: "40% reduction in water usage, 25% increase in crop yield",
//     prototypes: 3,
//     startupStatus: "Pre-seed",
//     funding: "$5,000",
//     timeline: "18 months",
//     members: 5,
//   },
//   {
//     id: "INN002",
//     title: "Mobile Learning Platform",
//     category: "EdTech",
//     stage: "Industrialization",
//     team: "EduConnect",
//     department: "Computer Science",
//     problemStatement: "Limited access to quality educational resources in rural areas",
//     solution: "Offline-first mobile app with curriculum-aligned content and AI tutoring",
//     impact: "Reached 10,000+ students, 85% improvement in test scores",
//     prototypes: 5,
//     startupStatus: "Seed Funded",
//     funding: "$50,000",
//     timeline: "24 months",
//     members: 8,
//   },
//   {
//     id: "INN003",
//     title: "Waste to Energy Converter",
//     category: "Green Energy",
//     stage: "Rollout",
//     team: "GreenTech Solutions",
//     department: "Environmental Science",
//     problemStatement: "Accumulation of organic waste and energy scarcity in communities",
//     solution: "Biogas generation system converting organic waste into cooking gas and electricity",
//     impact: "Processing 2 tons/day waste, powering 50 households",
//     prototypes: 4,
//     startupStatus: "Series A",
//     funding: "$200,000",
//     timeline: "36 months",
//     members: 12,
//   },
//   {
//     id: "INN004",
//     title: "Health Monitoring Wearable",
//     category: "HealthTech",
//     stage: "Incubation",
//     team: "HealthWatch",
//     department: "Biomedical Engineering",
//     problemStatement: "Delayed detection of health issues in elderly and chronic patients",
//     solution: "Low-cost wearable device monitoring vital signs with emergency alerts",
//     impact: "Early detection of 90% of critical health events",
//     prototypes: 2,
//     startupStatus: "Bootstrapped",
//     funding: "$10,000",
//     timeline: "12 months",
//     members: 4,
//   },
// ];