# Generated by Django 6.0 on 2025-12-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Physically Disabled', 'Physically Disabled'), ('Albino Students', 'Albino Students'), ('Hearing Impaired', 'Hearing Impaired'), ('Visually Impaired', 'Visually Impaired')], max_length=100, unique=True)),
                ('count', models.IntegerField(default=0)),
                ('color_variable', models.CharField(default='hsl(var(--primary))', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkForFeesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students_count', models.IntegerField(default=0)),
                ('total_hours', models.IntegerField(default=0)),
            ],
        ),
    ]
