# Generated by Django 6.0 on 2025-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
