# Generated by Django 5.2.8 on 2025-11-28 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0002_alter_student_program_delete_program"),
        ("faculties", "0002_alter_faculty_dean_alter_faculty_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Professor", "Professor"),
                            ("Lecturer", "Lecturer"),
                            ("Assistant", "Assistant Lecturer"),
                            ("Admin", "Administrative Staff"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Department name (e.g. Computer Science)",
                        max_length=100,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("PhD", "PhD"),
                            ("Masters", "Masters"),
                            ("Bachelors", "Bachelors"),
                            ("Diploma", "Diploma"),
                            ("Certificate", "Certificate"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "specialization",
                    models.TextField(blank=True, help_text="Area of Specialization"),
                ),
                ("date_joined", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="faculties.faculty",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="academic.institution",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff Members",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
