# Generated by Django 5.2.8 on 2025-12-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0003_department_alter_program_unique_together_and_more"),
        ("staff", "0002_vacancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="faculties.department",
            ),
        ),
    ]
