
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Rocket, DollarSign, Users, TrendingUp, MapPin, Zap } from "lucide-react";
import { 
    Table, 
    TableBody, 
    TableCell, 
    TableHead, 
    TableHeader, 
    TableRow 
} from "@/components/ui/table";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { StatsCard } from "@/components/dashboard/StatsCard";

// --- MOCK DATA ---
const STARTUP_STATS = {
    activeStartups: 12,
    totalRevenue: "ZWL 7.5M",
    peopleEmployed: 45,
    fundingAcquired: "USD 250K",
};

const STARTUP_DATA = [
    { name: "SolarFlow ZW", category: "Urban", institution: "Harare Poly", revenue: "ZWL 1.5M", employed: 8, status: "Scaling" },
    { name: "RuraFarm AI", category: "Rural", institution: "Chinhoyi Poly", revenue: "ZWL 800K", employed: 5, status: "Growth" },
    { name: "Mkoba Ed-App", category: "Urban", institution: "Mkoba TC", revenue: "ZWL 2.1M", employed: 12, status: "Stable" },
    { name: "MineSafe Tech", category: "Urban", institution: "Mutare Poly", revenue: "ZWL 450K", employed: 4, status: "Pre-seed" },
    { name: "Vending Solutions", category: "Rural", institution: "Bulawayo ITC", revenue: "ZWL 1.1M", employed: 10, status: "Scaling" },
];

// --- COMPONENT ---
export default function Startups() {
    return (
        <DashboardLayout>
            <div className="space-y-6">
                {/* Header */}
                <div className="pb-2 border-b">
                    <h1 className="text-3xl font-bold flex items-center gap-2">
                        <Rocket className="h-7 w-7 text-accent" />
                        Startups & Commercialisation
                    </h1>
                    <p className="text-muted-foreground">
                        Tracking economic impact, revenue, and employment generated by TESC-incubated ventures.
                    </p>
                </div>

                {/* Key Metrics */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                    <StatsCard
                        title="Active Startups"
                        value={STARTUP_STATS.activeStartups}
                        description="Currently registered ventures"
                        icon={Rocket}
                        variant="accent"
                    />
                    <StatsCard
                        title="Total Revenue"
                        value={STARTUP_STATS.totalRevenue}
                        description="Cumulative revenue generated"
                        icon={DollarSign}
                        variant="success"
                    />
                    <StatsCard
                        title="People Employed"
                        value={STARTUP_STATS.peopleEmployed}
                        description="Jobs created directly"
                        icon={Users}
                        variant="info"
                    />
                    <StatsCard
                        title="External Funding"
                        value={STARTUP_STATS.fundingAcquired}
                        description="Acquired in last 12 months"
                        icon={TrendingUp}
                        variant="default"
                    />
                </div>

                {/* Startups Detail Table */}
                <Card>
                    <CardHeader>
                        <CardTitle>Detailed Startup Performance</CardTitle>
                        <p className="text-sm text-muted-foreground">View financial status, employment, and focus areas.</p>
                    </CardHeader>
                    <CardContent>
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead>Startup Name</TableHead>
                                    <TableHead>Institution</TableHead>
                                    <TableHead>Category</TableHead>
                                    <TableHead className="text-right">Revenue (YTD)</TableHead>
                                    <TableHead className="text-center">Employed</TableHead>
                                    <TableHead>Status</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {STARTUP_DATA.map((startup) => (
                                    <TableRow key={startup.name}>
                                        <TableCell className="font-medium">{startup.name}</TableCell>
                                        <TableCell>{startup.institution}</TableCell>
                                        <TableCell>
                                            <span className={`px-2 py-1 text-xs font-medium rounded-full 
                                                ${startup.category === 'Urban' ? 'bg-indigo-100 text-indigo-700' :
                                                  'bg-amber-100 text-amber-700'
                                                }`}>
                                                {startup.category}
                                            </span>
                                        </TableCell>
                                        <TableCell className="text-right font-medium">{startup.revenue}</TableCell>
                                        <TableCell className="text-center">{startup.employed}</TableCell>
                                        <TableCell>
                                             <span className={`px-2 py-1 text-xs font-medium rounded-full 
                                                ${startup.status === 'Scaling' ? 'bg-green-100 text-green-700' :
                                                  startup.status === 'Growth' ? 'bg-blue-100 text-blue-700' :
                                                  'bg-gray-100 text-gray-700'
                                                }`}>
                                                {startup.status}
                                            </span>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </CardContent>
                </Card>
            </div>
        </DashboardLayout>
    );
}