import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Rocket, DollarSign, Users, TrendingUp, Loader2, FolderOpen } from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { StatsCard } from "@/components/dashboard/StatsCard";
import { getStartupStats } from "@/services/analysis.services"; // Check your import path

export default function Startups() {
    const [data, setData] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(false);

    useEffect(() => {
        getStartupStats()
            .then(setData)
            .catch((err) => {
                console.error("Failed to load startup data", err);
                setError(true);
            })
            .finally(() => setLoading(false));
    }, []);

    // 1. Loading State
    if (loading) {
        return (
            <DashboardLayout>
                <div className="flex justify-center h-[80vh] items-center">
                    <Loader2 className="h-8 w-8 animate-spin text-primary" />
                </div>
            </DashboardLayout>
        );
    }

    // 2. Helper for Currency formatting (safe against nulls)
    const formatMoney = (amount: number | undefined) => {
        if (amount === undefined || amount === null) return "$0";
        return new Intl.NumberFormat('en-US', { 
            style: 'currency', 
            currency: 'USD', 
            notation: "compact" 
        }).format(amount);
    };

    // 3. Safe Access to Data
    const stats = data?.stats || {};
    const listData = data?.list_data || [];
    const hasData = listData.length > 0;

    return (
        <DashboardLayout>
            <div className="space-y-6">
                
        {/* Header */}
        <div className="pb-2 border-b">
          <h1 className="text-2xl sm:text-3xl font-bold flex items-center gap-2">
            <Rocket className="h-6 w-6 sm:h-7 sm:h-7 text-accent" />
            Startups
          </h1>
          <p className="text-sm sm:text-base text-muted-foreground">
            Tracking economic impact generated by TESC-incubated ventures.
          </p>
        </div>

        {/* Key Metrics - defaults to 0 if data missing */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <StatsCard
            title="Active Startups"
            value={stats.activeStartups || 0}
            description="Currently registered"
            icon={Rocket}
            variant="accent"
          />
          <StatsCard
            title="Total Revenue"
            value={formatMoney(stats.totalRevenue)}
            description="Cumulative revenue"
            icon={DollarSign}
            variant="success"
          />
          <StatsCard
            title="People Employed"
            value={stats.peopleEmployed || 0}
            description="Jobs created directly"
            icon={Users}
            variant="info"
          />
          <StatsCard
            title="External Funding"
            value={formatMoney(stats.fundingAcquired)}
            description="Acquired funding"
            icon={TrendingUp}
            variant="default"
          />
        </div>

        {/* Detailed Table with Empty State */}
        <Card>
          <CardHeader className="p-4 sm:p-6">
            <CardTitle className="text-base sm:text-lg">Detailed Startup Performance</CardTitle>
          </CardHeader>
          <CardContent className="p-0 sm:p-6">
            <div className="rounded-md border-0 sm:border">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Startup Name</TableHead>
                    <TableHead className="hidden lg:table-cell">Institution</TableHead>
                    <TableHead className="hidden md:table-cell">Category</TableHead>
                    <TableHead className="text-right">Revenue</TableHead>
                    <TableHead className="text-center hidden sm:table-cell">Employed</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {hasData ? (
                    listData.map((startup: any, i: number) => (
                      <TableRow key={i}>
                        <TableCell className="font-medium text-xs sm:text-sm">
                          {startup.name}
                        </TableCell>
                        <TableCell className="hidden lg:table-cell text-xs">{startup.institution}</TableCell>
                        <TableCell className="hidden md:table-cell">
                          <span className={`px-2 py-1 text-[10px] font-medium rounded-full 
                                                        ${startup.category === 'Urban' ? 'bg-indigo-100 text-indigo-700' : 'bg-amber-100 text-amber-700'}`}>
                            {startup.category}
                          </span>
                        </TableCell>
                        <TableCell className="text-right text-xs sm:text-sm">{formatMoney(startup.revenue)}</TableCell>
                        <TableCell className="text-center hidden sm:table-cell text-xs">{startup.employed}</TableCell>
                        <TableCell>
                          <span className="capitalize text-[10px] sm:text-xs">{startup.status}</span>
                        </TableCell>
                      </TableRow>
                    ))
                  ) : (
                    // EMPTY STATE ROW
                    <TableRow>
                      <TableCell colSpan={6} className="h-48 text-center">
                        <div className="flex flex-col items-center justify-center text-muted-foreground">
                          <FolderOpen className="h-10 w-10 mb-2 opacity-20" />
                          <p className="font-medium text-sm">No startups found</p>
                          <p className="text-[10px]">
                            There are no industrilised projects recorded in the system yet.
                          </p>
                        </div>
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
            </div>
        </DashboardLayout>
    );
}
