# Generated by Django 5.2.3 on 2025-10-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The official name of the institution.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("TEACHERS_COLLEGE", "Teachers College"),
                            (
                                "INDUSTRIAL_TRAINING_COLLEGE",
                                "Industrial Training College",
                            ),
                            ("POLYTECHNIC", "Polytechnic"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "year_established",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The year the institution was established.",
                        null=True,
                    ),
                ),
                (
                    "student_capacity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of students the institution can accommodate.",
                    ),
                ),
                ("has_backup_power", models.BooleanField(default=False)),
                ("has_water_supply", models.BooleanField(default=False)),
                ("expansion_land_available", models.BooleanField(default=False)),
                (
                    "facilities_details",
                    models.TextField(
                        blank=True,
                        help_text="Describe the conditions of sporting facilities, classrooms, hostels, arts/culture facilities, and medical services.",
                    ),
                ),
                (
                    "infrastructure_details",
                    models.TextField(
                        blank=True,
                        help_text="Describe the state of the library, workshops, labs, and canteen.",
                    ),
                ),
                (
                    "student_support_details",
                    models.TextField(
                        blank=True,
                        help_text="Detail available student support: counseling, drug section, financial aid, scholarships, loans, etc.",
                    ),
                ),
                (
                    "partnerships_details",
                    models.TextField(
                        blank=True,
                        help_text="List any partnerships with other organizations or industries.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DATA_CLERK", "Data Clerk"),
                    ("VIEWER", "Viewer"),
                ],
                default="VIEWER",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.institution",
            ),
        ),
    ]
