# Generated by Django 5.2.3 on 2025-11-03 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
        ("users", "0002_institution_customuser_role_customuser_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academic.institution",
            ),
        ),
        migrations.DeleteModel(
            name="Institution",
        ),
    ]
