# Generated by Django 5.2.8 on 2025-11-20 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Polytechnic", "Polytechnic"),
                            ("Teachers College", "Teachers College"),
                            ("Industrial Training", "Industrial Training"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(help_text="e.g., Harare Province", max_length=100),
                ),
                ("address", models.TextField(blank=True)),
                ("capacity", models.PositiveIntegerField(default=0)),
                (
                    "staff",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of staff members"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Renovation", "Under Renovation"),
                            ("Closed", "Closed"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                (
                    "established",
                    models.PositiveIntegerField(
                        help_text="Year of establishment, e.g., 1980"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facilities",
                    models.ManyToManyField(blank=True, to="academic.facility"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Electrical Engineering", max_length=255
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("NC", "NC"),
                            ("ND", "ND"),
                            ("HND", "HND"),
                            ("1.1", "Level 1.1"),
                            ("2.1", "Level 2.1"),
                            ("3.1", "Level 3.1"),
                            ("Other", "Other"),
                        ],
                        help_text="e.g., HND",
                        max_length=20,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="academic.institution",
                    ),
                ),
            ],
            options={
                "unique_together": {("institution", "name", "level")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        help_text="Internal system ID, e.g., ST001",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 63-1234567A00",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("enrollment_year", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Attachment", "On Attachment"),
                            ("Graduated", "Graduated"),
                            ("Suspended", "Suspended"),
                            ("Deferred", "Deferred"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="academic.institution",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="academic.program",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
