# Generated by Django 5.2.8 on 2025-11-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
        ("faculties", "0002_alter_faculty_dean_alter_faculty_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="faculties.program",
            ),
        ),
        migrations.DeleteModel(
            name="Program",
        ),
    ]
