# Generated by Django 5.2.8 on 2025-11-28 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_alter_student_program_delete_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="facilities",
        ),
        migrations.AddField(
            model_name="facility",
            name="building",
            field=models.CharField(
                default="Main Building",
                help_text="Building name or number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="facility",
            name="contact_number",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="facility",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facility",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="equipment",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of equipment"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("Accommodation", "Accommodation"),
                    ("Laboratory", "Laboratory"),
                    ("Library", "Library"),
                    ("Sports", "Sports Facility"),
                    ("Innovation", "Innovation Center"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="institution",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilities",
                to="academic.institution",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facility",
            name="manager",
            field=models.CharField(
                default="Pending", help_text="Name of facility manager", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Maintenance", "Under Maintenance"),
                    ("Inactive", "Inactive"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="facility",
            unique_together={("institution", "name")},
        ),
    ]
