# Generated by Django 5.2.8 on 2025-11-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_remove_institution_facilities_facility_building_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Innovation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("agritech", "Agriculture Tech"),
                            ("edtech", "EdTech"),
                            ("healthtech", "HealthTech"),
                            ("fintech", "FinTech"),
                            ("greentech", "Green Energy"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("team_name", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(
                        help_text="Department backing this innovation", max_length=100
                    ),
                ),
                ("problem_statement", models.TextField()),
                ("proposed_solution", models.TextField()),
                ("team_size", models.PositiveIntegerField(default=1)),
                (
                    "timeline_months",
                    models.PositiveIntegerField(
                        help_text="Estimated timeline in months"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("idea", "Idea Phase"),
                            ("incubation", "Incubation"),
                            ("prototype", "Prototyping"),
                            ("market", "Market Ready"),
                        ],
                        default="idea",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innovations",
                        to="academic.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
