# Generated by Django 5.2.8 on 2025-12-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_innovation"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="final_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Distinction", "Distinction"),
                    ("Credit", "Credit"),
                    ("Pass", "Pass"),
                    ("Fail", "Fail"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="graduation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
