# Generated by Django 5.2.8 on 2025-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_student_final_grade_student_graduation_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="dropout_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Financial", "Financial Hardship"),
                    ("Academic", "Academic Failure"),
                    ("Medical", "Health/Medical"),
                    ("Personal", "Personal/Family Issues"),
                    ("Transfer", "Transfer to other Institution"),
                    ("Other", "Other"),
                ],
                help_text="Reason for dropout (only if status is Dropout)",
                max_length=50,
                null=True,
            ),
        ),
    ]
