# Generated by Django 5.2.8 on 2025-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="has_innovation_hub",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="institution",
            name="province",
            field=models.CharField(
                choices=[
                    ("Harare", "Harare"),
                    ("Bulawayo", "Bulawayo"),
                    ("Midlands", "Midlands"),
                    ("Manicaland", "Manicaland"),
                    ("Masvingo", "Masvingo"),
                    ("Mashonaland East", "Mashonaland East"),
                    ("Mashonaland West", "Mashonaland West"),
                    ("Mashonaland Central", "Mashonaland Central"),
                    ("Matabeleland North", "Matabeleland North"),
                    ("Matabeleland South", "Matabeleland South"),
                ],
                default="Harare",
                max_length=50,
            ),
        ),
    ]
