# Generated by Django 5.2.8 on 2025-12-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_institution_has_innovation_hub_institution_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Innovation',
        ),
    ]
