# Generated by Django 5.2.8 on 2025-12-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_delete_innovation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_payment_status',
            field=models.CharField(choices=[('Fully', 'Fully paid fees'), ('Partially', 'Partially paid fees'), ('Special', 'Special Fees Payment'), ('Waiver', 'Disable')], max_length=10, null=True),
        ),
    ]
