# Generated by Django 5.2.8 on 2025-12-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_delete_innovation'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='current_usage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
